# 端口
server:
  port: 9527

# 数据源配置
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/myuser?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 369000
      driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置