# 切换对应的环境  mysql
spring:
  redis:
    database: 0
    host: 8.131.236.94
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 100000
    password: redis@369000
  profiles:
    active: mysql


#Mybatis
mybatis-plus:
#mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.ljh.toll.entitys;
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印sql
    cache-enabled: true #二级缓存开启








